version: '3.8'

services:
    postgres:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=file-management
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        ports:
            - '5050:80'
        depends_on:
            - postgres
        volumes:
            - pgadmin4_data:/var/lib/pgadmin

volumes:
    postgres_data:
    pgadmin4_data:
